# Site settings
title: soderparr.com Communication Service
email: matt@mattrude.com
description: ""
url: "https://soderparr.com"
name: "soderparr.com"
baseurl: ""

owner_name: "Matt Rude"
owner_url: "https://mattrude.com"

# Analytics settings
#google_analytics_id: 

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- Gemfile
- Gemfile.lock
- README.md
- CONTRIBUTING.md
- LICENSE
- site-builder.sh

gems:
- jekyll-sitemap
#- jekyll-press

jekyll-press:
  exclude: 'robots.txt, assets/css/custom.css' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
