# Site settings
title: soderparr.com Communication Service
email: matt@mattrude.com
description: ""
url: "https://soderparr.com"
name: "soderparr.com"
baseurl: ""
destination: "/var/www/soderparr.com"

owner_name: "Matt Rude"
owner_url: "https://mattrude.com"

# Analytics settings
#google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- Gemfile
- Gemfile.lock
- README.md
- CONTRIBUTING.md
- LICENSE

gems:
- jekyll-sitemap
#- jekyll-minifier

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
